# These are supported funding model platforms

ko_fi: saveriomorelli
liberapay: Sav22999
custom: ["https://www.paypal.me/saveriomorelli", "https://www.gofundme.com/manage/cv-android"]
github: [Sav22999]
